config/routes.rb
Poker::Application.routes.draw do
  resources :games do
    resources :players, :only => [:create, :destroy, :index, :show], :controller => 'game_players' do
      post :addon
      put :exit
    end
  end

  match 'chips/:id' => 'game_players#chips', :as => 'chips'

  resources :locations, :except => [:index]

  resources :players, :execpt => [:index] do
    get :stats
  end

  get "login/new", :as => 'login'
  post "login" => 'login#create', :as => 'login'
  match "logout" => 'login#destroy', :as => 'logout'

  unless Rails.env.production?
    get "login/now", :as => 'login_now'
  end

  root :to => 'games#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :location
  has_many :game_players
  has_many :players, :through => :game_players
  attr_accessible :on, :location_id, :buyin_chips, :buyin_amount, :rebuy_chips, :rebuy_amount

  validates_presence_of :location_id
  validates_presence_of 'on'

  validate :on_is_a_date


  def non_players
    (Player.all - players)
  end

  def save_with_player(player)
    ActiveRecord::Base.transaction do
      begin
        save!
        self.players << player
        return self
      rescue ActiveRecord::RecordInvalid
        raise ActiveRecord::Rollback
      end
    end
    false
  end

  def on_is_a_date
    return if on.blank? or on.is_a?(Date)
    Date.parse(on)
  rescue ArgumentError
    return false
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :require_login
  before_filter :require_owner, :only => [:edit, :update]

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new(params[:game] || {})
  end

  def create
    @game = Game.new(params[:game])
    if @game.save_with_player(current_user)
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(params[:game])
      redirect_to game_path(@game)
    else
      render :edit
    end
  end

  def index
    @games = Game.includes(:location).order('"on" desc, locations.name').all
  end

private

  def require_owner

  end
end

app/views/games/_fields.html.haml
%div
  = f.label :location_id, 'Location'
  = f.collection_select(:location_id, Location.owner_by(current_user).order(:name), 'id', 'name')
  = link_to 'Create new location', new_location_path
  = error_for(f, :location_id, 'Location')

%div
  = f.label :on, 'Played on'
  = f.text_field(:on, :type => 'date')
  = error_for(f, :on, 'Played on')

%h2
  Buy-In
%div
  = f.label :buyin_chips, 'Chips'
  = f.text_field(:buyin_chips, :type => 'number', :min => 1000, :max => 100000, :step => 1000)

  = f.label :buyin_amount, 'Amount'
  = f.text_field(:buyin_amount, :type => 'number', :min => 0, :max => 20, :step => 1)

%h2
  Rebuy
%div
  = f.label :rebuy_chips, 'Chips'
  = f.text_field(:rebuy_chips, :type => 'number', :min => 500, :max => 100000, :step => 500)

  = f.label :rebuy_amount, 'Amount'
  = f.text_field(:rebuy_amount, :type => 'number', :min => 0, :max => 20, :step => 1)

app/views/games/edit.html.haml
%h1 Edit Game

= form_for @game do |f|
  = render :partial => 'fields', :locals => {:f => f}

  .buttons
    = f.submit 'Update'
    = link_to 'Cancel', game_path(@game), :class => 'button'

app/views/games/index.html.haml
%h1 Games

= link_to 'Create new game', new_game_path, :class => 'button'

%table
  %thead
    %tr
      %th
        Location
      %th
        Played On
  %tbody
    - @games.each do |game|
      %tr
        %td
          = link_to game.location.name, game_path(game)
        %td
          = game.on.strftime('%d %b %Y')

app/views/games/new.html.haml
%h1 New Game

= form_for @game do |f|
  = render :partial => 'fields', :locals => {:f => f}

  .buttons
    = f.submit 'Create'
    = link_to 'Cancel', games_path, :class => 'button'

app/views/games/show.html.haml
%h1
  = "'#{@game.location.name}'"
  .small
    on
  = @game.on.strftime('%d %b %y')

- if @game.rebuy_chips
  .details
    .label
      (A) Addon:
    = number_with_delimiter @game.rebuy_chips
    chips for
    = "£#{@game.rebuy_amount}"

.details
  .label
    (E) Out of chips

.details
  .label
    (PS) Player Stats

%table#players
  %thead
    %tr
      %th
        Players
  %tbody
    - @game.players.each do |player|
      %tr.player
        %td
          .actions
            = link_to 'A', game_player_addon_path(@game, player), :title => 'Buy Addon', :method => 'post'
            |
            = link_to 'E', game_player_exit_path(@game, player), :title => 'Exit Game', :method => 'put'
            |
            = link_to 'PS', player_stats_path(player, :from => request.env['REQUEST_URI']), :title => 'Player stats', :method => 'get'
          = link_to player.details(@game).join('<br/>').html_safe, game_player_path(@game, player)


.buttons
  = link_to 'Change player list', game_players_path(@game), :class => 'button'
.buttons
  = link_to 'Edit', edit_game_path(@game), :class => 'button'
  = link_to 'Games', games_path, :class => 'button'