config/routes.rb
Poker::Application.routes.draw do
  resources :games do
    resources :players, :only => [:create, :destroy, :index, :show], :controller => 'game_players' do
      post :addon
      put :exit
    end
  end

  match 'chips/:id' => 'game_players#chips', :as => 'chips'

  resources :locations, :except => [:index]

  resources :players, :execpt => [:index] do
    get :stats
  end

  get "login/new", :as => 'login'
  post "login" => 'login#create', :as => 'login'
  match "logout" => 'login#destroy', :as => 'logout'

  unless Rails.env.production?
    get "login/now", :as => 'login_now'
  end

  root :to => 'games#index'

end

app/models/game_player.rb
class GamePlayer < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  attr_accessible :game_id, :player_id, :position
  has_many :chips

  after_create :add_buyin_chips

  def add_buyin_chips
    if game.buyin_chips
      chips.create(chips: game.buyin_chips, amount: game.buyin_amount)
    end
  end

  def add_rebuy_chips
    if game.rebuy_chips
      chips.create(chips: game.rebuy_chips, amount: game.rebuy_amount)
    end
  end

  def exit_game
    update_attributes(:position => game.game_players.reject(&:position).count)
  end
end

app/controllers/game_players_controller.rb
class GamePlayersController < ApplicationController
  before_filter :require_login
  before_filter :load_game, :except => [:index, :create]
  before_filter :load_game_with_player, :only => [:create]

  def create
    @game.players += [@player]

    redirect_to game_path(@game)
  end

  def destroy
    @game.players -= [@player]

    redirect_to game_path(@game)
  end

  def exit
    @player.exit_game(@game)

    redirect_to game_path(@game)
  end

  def addon
    @player.add_rebuy_chips(@game)

    redirect_to game_path(@game)
  end

  def index
    @game = Game.find(params[:game_id])
    @non_players = Player.where(['id not in (?)', @game.players.map(&:id)])
  end

  def show
    @game_player = @player.player_game(@game)
  end

private

  def load_game
    @game = Game.find(params[:game_id])
    @player = Player.find(player_id)
  end

  def load_game_with_player
    @game = Game.find(params[:game_id])
    if player_id
      @player = Player.find(player_id)
    else
      @player = Player.create(
        name: "#{params[:guest_name]} (Guest)",
        password: 'password',
        password_confirmation: 'password'
      )
    end
  end

  def player_id
    params[:id] || params[:player_id]
  end
end

app/views/game_players/index.html.haml
%h1
  Player for:
  = "'#{@game.location.name}'"
  .small
    on
  = @game.on.strftime('%d %b %y')


%table#players
  %thead
    %tr
      %th
        Players
  %tbody
    - @game.players.each do |player|
      %tr.player
        %td
          .actions
            = link_to 'Remove', game_player_path(@game.id, player), :title => 'Remove player', :method => 'delete'
          = player.full_identity

%table#non-players
  %thead
    %tr
      %th
        Non Players
  %tbody
    - @non_players.each do |player|
      %tr.player
        %td
          .actions
            = link_to 'Add', game_players_path(@game, player_id: player.id), :title => 'Remove player', :method => 'post'
          = player.full_identity
    %tr.player
      %td
        = form_tag url: game_players_path(@game) do
          .actions
            = submit_tag 'Add'
          = label_tag :guest_name, 'Guest player name'
          = text_field_tag :guest_name, params[:guest_name]

.buttons
  = link_to 'Back', game_path(@game), :class => 'button'

app/views/game_players/show.html.haml
%h1
  = @player.identity
  @
%h1
  = @game.location.name
  .small
    on
  = @game.on.strftime('%d %b %Y')

Current chips
= @game_player.current_chips

.buttons
  = link_to '+100', chips_path(id: @game_player.id, change: 100), class: 'button chips', method: 'put', :'data-chips' => 100
  = link_to '+1,000', chips_path(id: @game_player.id, change: 1000), class: 'button chips', method: 'put', :'data-chips' => 1000
  = link_to '+10,000', chips_path(id: @game_player.id, change: 10000), class: 'button chips', method: 'put', :'data-chips' => 10000

.buttons
  = link_to '-100', chips_path(id: @game_player.id, change: -100), class: 'button chips', method: 'put', :'data-chips' => -100
  = link_to '-1,000', chips_path(id: @game_player.id, change: -1000), class: 'button chips', method: 'put', :'data-chips' => -1000
  = link_to '-10,000', chips_path(id: @game_player.id, change: -10000), class: 'button chips', method: 'put', :'data-chips' => -10000