config/routes.rb
Poker::Application.routes.draw do
  resources :games do
    resources :players, :only => [:create, :destroy, :index, :show], :controller => 'game_players' do
      post :addon
      put :exit
    end
  end

  match 'chips/:id' => 'game_players#chips', :as => 'chips'

  resources :locations, :except => [:index]

  resources :players, :execpt => [:index] do
    get :stats
  end

  get "login/new", :as => 'login'
  post "login" => 'login#create', :as => 'login'
  match "logout" => 'login#destroy', :as => 'logout'

  unless Rails.env.production?
    get "login/now", :as => 'login_now'
  end

  root :to => 'games#index'

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    if @player = Player.login(params[:name], params[:password])
      session[:user_id] = @player.id
      redirect_last_or_root
    else
      @player ||= Player.new(params.slice(:name))
      render :new, :status => 404
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def now
    raise 'for test and dev only' if Rails.env.production?
    session[:user_id] = params[:id]
    redirect_last_or_root
  end
end

app/views/login/new.html.haml
%h1 Login

= form_tag login_path do
  %div
    = label_tag :name, 'Username'
    = text_field_tag :name, @player.name

  %div
    = label_tag :password
    = password_field_tag :password, ''

  - if response.code =~ /^4/
    .errors
      Invalid username/password


  .buttons
    = submit_tag 'Login'
    = link_to 'Create new player', new_player_path